# Demonstrate the features of the
# Heltec Wireless Stick Lite V3
substitutions:
  name: "heltec-wsl-v3-demo"
  friendly_name: "Heltec WSL V3 Demo"
  room: ""
  device_description: "heltec wsl v3 demo "
  project_name: "Heltec.WSL V3 Demo"
  project_version: "1.0"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: heltec_wifi_lora_32_V3
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.9
    # version: 2.0.10
    platform_version: 6.4.0
  # restore_from_flash: true

# preferences:
#   flash_write_interval: 1min

# Enable Home Assistant API
api:

ota:
    
logger:

mdns:
  disabled: false

web_server:
  port: 80

wifi:
   # This spawns an AP with the device name and mac address with no password.
  ap: {}

captive_portal:
  
dashboard_import:
  package_import_url: github://PaulSchulz/esphome-heltec-configs/heltec-wsl-v3-demo.yaml

#############################################################################
light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO35
    
switch:
  - platform: gpio
    pin: 14
    name: "Pin 14"

  - platform: gpio
    pin: 21
    name: "Pin 21"

  - platform: gpio
    pin: 39
    name: "Pin 39"
    
  - platform: gpio
    pin: 40
    name: "Pin 40"
    
  - platform: gpio
    pin: 41
    name: "Pin 41"
    
  - platform: gpio
    pin: 42
    name: "Pin 42"
    
  - platform: gpio
    pin: 45
    name: "Pin 45"

  - platform: gpio
    pin: 46
    name: "Pin 46"

  - platform: gpio
    pin: 47
    name: "Pin 47"    

  - platform: gpio
    pin: 48
    name: "Pin 48"
